=== Igalia/phpreport-legacy/rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT weeklyDedication (dedication+)>
 <!ELEMENT dedication (dailyDedication+)>
 <!ELEMENT dailyDedication (task+)>
 <!ELEMENT task (#PCDATA)>
 
 <!ATTLIST dedication 
  month (January|February|March|April|May|June|July|August|September|October|November|December|january|february|march|april|may|june|july|august|september|october|november|december)  #REQUIRED>
 <!ATTLIST dailyDedication day CDATA #REQUIRED>
 <!ATTLIST task 
  type () #REQUIRED
  start CDATA #REQUIRED
  end CDATA #REQUIRED
  name ()
  phase (construccion|elaboracion|explotacion|inicio|transicion) #IMPLIED
  ttype (analisis|comunidad|coordinacion|demo|despliegue|diseno|documentacion|entorno|formacion|implementacion|mantenimiento|mto_sistemas|prueba|publicacion|requisitos|tecnologia) #IMPLIED
  story CDATA #IMPLIED
  telework (true) #IMPLIED>

=== Igalia/phpreport-legacy/doc/test_xml_reports/weeklyreport-admin-2006-01-09-2006-01-15.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE weeklyDedication SYSTEM "rules.dtd">

<weeklyDedication>
<dedication month="January">
<dailyDedication day="9">
<task type="SYS" start="1000" end="1030">
System task
</task>
<task type="PEX" name="test1" phase="construction"
       start="1030" end="1500">

</task>
<task type="PEX" name="test1" phase="construction"
       start="1530" end="2000" telework="true">
Work on project test1
</task>
</dailyDedication>

<dailyDedication day="10">
<task type="PEX" name="test1" phase="construction"
       start="1100" end="1430">
Work on project test1
</task>
<task type="PEX" name="test1" phase="construction"
       start="1530" end="2000">
Work on project test1
</task>
</dailyDedication>

<dailyDedication day="11">
<task type="PEX" name="test1" phase="construction"
       start="1100" end="1430">
Work on project test1
</task>
<task type="PEX" name="test1" phase="construction"
       start="1600" end="2100">
Work on project test1
</task>
</dailyDedication>

<dailyDedication day="12">
<task type="PEX" name="test1" phase="construction"
       start="1100" end="1430">
Work on project test1
</task>
<task type="PEX" name="test1" phase="construction"
       start="1530" end="2000">
Work on project test1 (reuni√≥n Santiago)
</task>
</dailyDedication>

<dailyDedication day="13">
<task type="COR" start="1000" end="1400">
Coordination meeting
</task>
<task type="COR" start="1600" end="2000">
Coordination meeting
</task>
</dailyDedication>

</dedication>
</weeklyDedication>
